tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "tertiary-fixed": "#ff9479",
              "primary-fixed": "#d1fc00",
              "on-secondary": "#004d57",
              "inverse-surface": "#f9f9fd",
              "on-surface": "#f9f9fd",
              "on-primary": "#546600",
              "surface-container-high": "#1d2024",
              "on-primary-fixed": "#3c4a00",
              "error-dim": "#d53d18",
              "secondary-fixed": "#26e6ff",
              "surface-container-lowest": "#000000",
              "surface-variant": "#23262a",
              "on-primary-container": "#4c5d00",
              "surface-container-low": "#111417",
              "tertiary-container": "#fc3c00",
              "outline": "#747579",
              "inverse-on-surface": "#535559",
              "secondary": "#00e3fd",
              "surface-bright": "#292c31",
              "tertiary-fixed-dim": "#ff7d5c",
              "primary-dim": "#c7ef00",
              "on-tertiary-container": "#000000",
              "tertiary-dim": "#dc3300",
              "error": "#ff7351",
              "outline-variant": "#46484b",
              "on-surface-variant": "#aaabaf",
              "primary-fixed-dim": "#c4ec00",
              "tertiary": "#ff7350",
              "primary": "#f4ffc6",
              "on-secondary-fixed-variant": "#005964",
              "secondary-dim": "#00d4ec",
              "secondary-container": "#006875",
              "on-primary-fixed-variant": "#556800",
              "on-error-container": "#ffd2c8",
              "on-secondary-container": "#e8fbff",
              "secondary-fixed-dim": "#00d7f0",
              "on-error": "#450900",
              "on-tertiary-fixed": "#360600",
              "surface": "#0c0e11",
              "inverse-primary": "#546600",
              "on-background": "#f9f9fd",
              "surface-container-highest": "#23262a",
              "on-tertiary": "#440900",
              "on-secondary-fixed": "#003a42",
              "surface-tint": "#f4ffc6",
              "surface-container": "#171a1d",
              "surface-dim": "#0c0e11",
              "primary-container": "#d1fc00",
              "background": "#0c0e11",
              "error-container": "#b92902",
              "on-tertiary-fixed-variant": "#721600"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "fontFamily": {
              "headline": ["Lexend"],
              "body": ["Manrope"],
              "label": ["Manrope"]
      }
    },
  },
}
